// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Comment struct {
	ID        int64       `json:"id"`
	CreatedAt interface{} `json:"createdAt"`
	UpdatedAt interface{} `json:"updatedAt"`
	MediaID   int64       `json:"mediaId"`
	UserID    int64       `json:"userId"`
	ParentID  interface{} `json:"parentId"`
	Content   string      `json:"content"`
}

type Friend struct {
	UserID   int64 `json:"userId"`
	FriendID int64 `json:"friendId"`
}

type MediaTag struct {
	CreatedAt interface{} `json:"createdAt"`
	MediaID   int64       `json:"mediaId"`
	TagID     int64       `json:"tagId"`
}

type Medium struct {
	ID        int64       `json:"id"`
	CreatedAt interface{} `json:"createdAt"`
	UpdatedAt interface{} `json:"updatedAt"`
	Uuid      string      `json:"uuid"`
	Title     string      `json:"title"`
	Desc      interface{} `json:"desc"`
	UserID    int64       `json:"userId"`
	Type      string      `json:"type"`
	Format    string      `json:"format"`
	Md5       string      `json:"md5"`
}

type Tag struct {
	ID        int64       `json:"id"`
	CreatedAt interface{} `json:"createdAt"`
	Content   string      `json:"content"`
}

type User struct {
	ID           int64       `json:"id"`
	CreatedAt    interface{} `json:"createdAt"`
	UpdatedAt    interface{} `json:"updatedAt"`
	Uuid         string      `json:"uuid"`
	DisplayName  string      `json:"displayName"`
	FirstName    string      `json:"firstName"`
	LastName     string      `json:"lastName"`
	PasswordHash string      `json:"passwordHash"`
	PasswordSalt string      `json:"passwordSalt"`
	Bio          interface{} `json:"bio"`
	AvatarUrl    interface{} `json:"avatarUrl"`
	TotpSecret   interface{} `json:"totpSecret"`
	RefreshJti   interface{} `json:"refreshJti"`
}
