version: "2"
sql:
  - engine: sqlite
    schema: "schema.sql"
    queries: "../pkg/database"
    gen:
      go:
        out: "../pkg/database"
        package: database
        emit_empty_slices: true
        emit_json_tags: true
        emit_pointers_for_null_types: true
        emit_sql_as_comment: true
        json_tags_case_style: camel
        output_db_file_name: db.sql.go
        output_models_file_name: models.sql.go
        query_parameter_limit: 0
